#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: cloud-site-manager

resources:
- namespace.yaml
- imagepullsecret.yaml
- crd-site.yaml
- deployment.yaml
- serviceaccount-role.yaml
- serviceaccount-rolebinding.yaml
- serviceaccount.yaml
- sitemgr-service.yaml

images:
- name: sitemgr
  newName: nvcr.io/nvidian/nvforge-devel/cloud-site-manager
  newTag: v0.1.16-4-g8d0b81a
