apiVersion: v1
kind: Service
metadata:
  name: {{ include "carbide-rest-api.name" . }}
  namespace: {{ include "carbide-rest-api.namespace" . }}
  labels:
    {{- include "carbide-rest-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      name: metrics
  selector:
    {{- include "carbide-rest-api.selectorLabels" . | nindent 4 }}
{{- if .Values.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carbide-rest-api.name" . }}-nodeport
  namespace: {{ include "carbide-rest-api.namespace" . }}
  labels:
    {{- include "carbide-rest-api.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.nodePort.port }}
      name: http
  selector:
    {{- include "carbide-rest-api.selectorLabels" . | nindent 4 }}
{{- end }}
