---
apiVersion: v1
kind: Service
metadata:
  name: ipam
  namespace: carbide-system
  labels:
    app: ipam
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc
  selector:
    app: ipam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam
  namespace: carbide-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
        tier: api
    spec:
      containers:
        - name: ipam
          image: localhost:5000/carbide-rest-ipam:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/ipam-server"]
          args: ["postgres"]
          ports:
            - containerPort: 9090
              name: grpc
          env:
            - name: GOIPAM_PG_HOST
              value: postgres.carbide-system.svc.cluster.local
            - name: GOIPAM_PG_PORT
              value: "5432"
            - name: GOIPAM_PG_USER
              value: goipam
            - name: GOIPAM_PG_PASSWORD
              value: goipam
            - name: GOIPAM_PG_DBNAME
              value: goipam
            - name: GOIPAM_PG_SSLMODE
              value: disable
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

