#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: elektra-site-agent
      app.kubernetes.io/component: site-agent
    includeSelectors: true

resources:
  - elektra-svc.yaml
  - elektra-sts.yaml
  - sa-role.yaml
  - sa-rolebinding.yaml
  - sa.yaml
