#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: cloud-db

resources:
  - namespace.yaml
  - imagepullsecret.yaml
  - configmap.yaml
  - job.yaml

images:
  - name: cloud-db
    newName: nvcr.io/nvidian/nvforge-devel/cloud-db
    newTag: v0.1.47
