apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sites.forge.nvidia.io
spec:
  group: forge.nvidia.io
  names:
    kind: Site
    listKind: SiteList
    plural: sites
    singular: site
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                uuid:
                  type: string
                sitename:
                  type: string
                provider:
                  type: string
                fcorg:
                  type: string
            status:
              type: object
              properties:
                otp:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    passcode:
                      type: string
                    expiry:
                      type: string
                    timestamp:
                      type: string
                bootstrapstate:
                  type: string
                controlplanestatus:
                  type: string
      subresources:
        status: {}

