apiVersion: v1
kind: Secret
data:
  otp: QXV0b0dlbmVyYXRlZA==
  cacertificate: QXV0b0dlbmVyYXRlZA==
  certificate: QXV0b0dlbmVyYXRlZA==
  key: QXV0b0dlbmVyYXRlZA==
metadata:
  name: temporal-cert
  namespace: elektra-site-agent
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
---
