#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: elektra-site-agent
      app.kubernetes.io/component: grpc-client
    includeSelectors: true

resources:
  - grpc-client.yaml
  - cert-policy.yaml
  - cert-role-binding.yaml
  - cert-role.yaml
