apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carbide-rest-workflow.name" . }}-config
  namespace: {{ include "carbide-rest-workflow.namespace" . }}
  labels:
    {{- include "carbide-rest-workflow.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
