---
apiVersion: v1
kind: Namespace
metadata:
  name: carbide-system
  labels:
    name: carbide-system
    tier: control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: carbide-site
  labels:
    name: carbide-site
    tier: edge

