#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-workflow-config
data:
  config.yaml: |+
    env:
      dev: false

    log:
      level: debug

    db:
      host: forge-pg-cluster.postgres.svc.cluster.local
      port: 5432
      name: forge
      user: forge
      passwordPath: /var/secrets/db/auth/password

    temporal:
      host: temporal-frontend-headless.temporal.svc.cluster.local
      port: 7233
      serverName: localhost
      namespace: cloud
      queue: cloud
      tls:
        certPath: /var/secrets/temporal/certs/client-cloud/tls.crt
        keyPath: /var/secrets/temporal/certs/client-cloud/tls.key
        caPath: /var/secrets/temporal/certs/client-cloud/ca.crt
      encryptionKey: "carbide-rest"

    ngc:
      api:
        baseUrl: https://test.com

    siteManager:
      svcEndpoint: "https://sitemgr.cloud-site-manager:8100/v1/site"
    
    tracing:
      enabled: false
      serviceName: cloud-workflow
