#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: cloud-workflow

resources:
  - namespace.yaml
  - imagepullsecret.yaml
  - service.yaml
  - configmap.yaml
  - deployment.yaml
