#

apiVersion: v1
kind: Service
metadata:
  name: cloud-worker
  labels:
    app: cloud-worker
spec:
  ports:
    - name: http
      port: 8899
      targetPort: 8899
      protocol: TCP
    - name: metrics
      port: 9360
      targetPort: 9360
      protocol: TCP
  selector:
    app: cloud-worker
---
apiVersion: v1
kind: Service
metadata:
  name: site-worker
  labels:
    app: site-worker
spec:
  ports:
    - name: http
      port: 8899
      targetPort: 8899
      protocol: TCP
    - name: metrics
      port: 9360
      targetPort: 9360
      protocol: TCP
  selector:
    app: site-worker
