#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-api-config
data:
  config.yaml: |+
    env:
      dev: false
      disconnected: true

    api:
      name: carbide
      route:
        version: v2

    log:
      level: info
      sentry:
        dsn: ""

    db:
      host: forge-pg-cluster.postgres.svc.cluster.local
      port: 5432
      name: forge
      user: forge
      passwordPath: /var/secrets/db/auth/password

    temporal:
      host: temporal-frontend-headless.temporal.svc.cluster.local
      port: 7233
      serverName: localhost
      namespace: cloud
      queue: cloud
      tls:
        enabled: true
        certPath: /var/secrets/temporal/certs/client-cloud/tls.crt
        keyPath: /var/secrets/temporal/certs/client-cloud/tls.key
        caPath: /var/secrets/temporal/certs/client-cloud/ca.crt
      encryptionKey: "carbide"

    issuers:
      - name: kas-legacy
        origin: kas-legacy
        jwks: https://authn.nvidia.com/pubJWKS
        issuer: "authn.nvidia.com"

    siteManager:
      enabled: true
      svcEndpoint: "https://sitemgr.cloud-site-manager:8100/v1/site"

    site:
      phoneHomeUrl: http://169.254.169.254:7777/latest/meta-data/phone_home

    metrics:
      enabled: true
      port: 9360

    tracing:
      enabled: false
      serviceName: cloud-api
      
    keycloak:
      enabled: false
