#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: cloud-api

resources:
- namespace.yaml
- imagepullsecret.yaml
- ssa-placeholder-secret.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
