#

apiVersion: v1
kind: Service
metadata:
  name: cloud-api
  labels:
    app: cloud-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8388
      protocol: TCP
    - name: metrics
      port: 9360
      targetPort: 9360
      protocol: TCP
  selector:
    app: cloud-api
