#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: elektra-site-agent

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: site-agent

resources:
  - namespace.yaml
  - grpc-client
  - site-agent

configMapGenerator:
  - name: elektra-config-map
    env: files/config.properties
  - name: elektra-database-config
    behavior: create
    literals:
      - DB_HOST=forge-pg-cluster.postgres.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=elektra
      - SECRET_REF=elektra-site-agent.elektra.forge-pg-cluster.credentials.postgresql.acid.zalan.do
