# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-site-agent-worker-1
  namespace: cloud-workflow
  labels:
    app: test-site-agent-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-site-agent-worker-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test-site-agent-worker-1
    spec:
      containers:
        - name: test-site-agent-worker-1
          image: localhost:5001/test-site-agent:local-dev
          imagePullPolicy: Always
          env:
            # Config file path
            - name: CONFIG_FILE_PATH
              value: /etc/cloud-workflow/config.yaml
            # Temporal namespace this worker will operate on
            - name: TEMPORAL_NAMESPACE
              value: c8ddbffa-e649-42a0-bc71-3b9bc1134920
            # Temporal queue this worker will operate on
            - name: TEMPORAL_QUEUE
              value: site
          volumeMounts:
            - name: cloud-workflow-config
              mountPath: /etc/cloud-workflow/
              readOnly: true
            - name: temporal-client-cloud-certs
              mountPath: /var/secrets/temporal/certs/client-cloud/
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8899
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8899
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: cloud-workflow-config
          configMap:
            name: cloud-workflow-config
        - name: temporal-client-cloud-certs
          secret:
            secretName: temporal-client-cloud-certs
