replicaCount: 1

nameOverride: ""
namespaceOverride: ""

image:
  name: carbide-rest-api

service:
  type: ClusterIP
  port: 8388
  metricsPort: 9360

nodePort:
  enabled: false
  port: 30388

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

secrets:
  carbideSecrets: carbide-secrets
  temporalClientCerts: temporal-client-certs

config:
  env:
    dev: true
    disconnected: true
  api:
    name: carbide
    route:
      version: v2
  log:
    level: debug
    sentry:
      dsn: ""
  db:
    host: postgres
    port: 5432
    name: forge
    user: forge
    password: forge
  temporal:
    host: temporal-frontend.temporal
    port: 7233
    serverName: server.temporal.local
    namespace: cloud
    queue: cloud
    tls:
      enabled: true
      certPath: /var/secrets/temporal/certs/tls.crt
      keyPath: /var/secrets/temporal/certs/tls.key
      caPath: /var/secrets/temporal/certs/ca.crt
      disableHostVerification: false
    encryptionKeyPath: /var/secrets/temporal/encryption-key
  siteManager:
    enabled: true
    svcEndpoint: "https://carbide-rest-site-manager:8100/v1/site"
  metrics:
    enabled: true
    port: 9360
  tracing:
    enabled: false
    serviceName: cloud-api
  keycloak:
    enabled: true
    baseURL: http://keycloak:8080
    externalBaseURL: http://localhost:8080
    realm: carbide-dev
    clientID: carbide-api
    clientSecretPath: /var/secrets/keycloak/client-secret
    serviceAccount: true
  rateLimiter:
    enabled: false
    rate: 10.0
    burst: 30
    expiresIn: 180
