# carbide-rest-cert-manager Service (native Go PKI)
apiVersion: v1
kind: Service
metadata:
  name: carbide-rest-cert-manager
  labels:
    app: carbide-rest-cert-manager
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: https
    - port: 8001
      targetPort: 8001
      name: http
  selector:
    app: carbide-rest-cert-manager
