#
---
# Source: cert-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: credsmgr
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: credsmgr
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: credsmgr
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app.kubernetes.io/name: credsmgr
