# carbide-rest-site-agent Service
apiVersion: v1
kind: Service
metadata:
  name: carbide-rest-site-agent
  labels:
    app: carbide-rest-site-agent
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 2112
      targetPort: 2112
      name: metrics
  selector:
    app: carbide-rest-site-agent

