# carbide-rest-elektraserver Service
apiVersion: v1
kind: Service
metadata:
  name: carbide-rest-elektraserver
  labels:
    app: carbide-rest-elektraserver
spec:
  type: ClusterIP
  ports:
    - port: 11079
      targetPort: 11079
      name: grpc
  selector:
    app: carbide-rest-elektraserver

