- - :license
  - github.com/nvidia/carbide-rest-api-snapshot/carbide-rest-api-schema
  - Nvidia Proprietary
  - :who: NVIDIA
    :why: NVIDIA package for partners
    :versions: []
    :when: 2022-07-14 00:00:00.000000000 Z
- - :permit
  - MIT
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - Apache 2.0
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - BSD-3-Clause
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - BSD Zero Clause License
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - Simplified BSD
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - CC0-1.0
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - CC0-BY-4.0
  - :who: NVIDIA
    :why: Included in the automatic approvals
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - Nvidia Proprietary
  - :who: NVIDIA
    :why: Nvidia Package
    :versions: []
    :when: 2022-10-04 00:00:00.000000000 Z
