version: '3.8'

services:
  postgres:
    image: postgres
    container_name: psm_postgres
    environment:
      POSTGRES_USER: psmuser
      POSTGRES_PASSWORD: psmpassword
      POSTGRES_DB: psmdatabase
    ports:
      - "5432:5432"
    networks:
      - my_network

  vault:
    image: vault:1.9.3
    container_name: my_vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: psmvaultroot
      VAULT_LOCAL_CONFIG: >
        {
          "backend": {"file": {"path": "/vault/file"}},
          "listener": {"tcp": {"address": "0.0.0.0:8201", "tls_disable": 1}},
          "ui": true,
          "api_addr": "http://127.0.0.1:8201"
        }
    ports:
      - "8201:8201"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

