{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "carbide-rest-site-agent.name" . }}-grpc-client-cert
  namespace: {{ include "carbide-rest-site-agent.namespace" . }}
  labels:
    {{- include "carbide-rest-site-agent.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  subject:
    organizations:
      - Nvidia
  isCA: false
  privateKey:
    algorithm: {{ .Values.certificate.privateKey.algorithm }}
    size: {{ .Values.certificate.privateKey.size }}
  usages:
    - client auth
  dnsNames:
    - {{ include "carbide-rest-site-agent.name" . }}
    - {{ include "carbide-rest-site-agent.name" . }}.{{ include "carbide-rest-site-agent.namespace" . }}
    - {{ include "carbide-rest-site-agent.name" . }}.{{ include "carbide-rest-site-agent.namespace" . }}.svc.cluster.local
  uris:
    - spiffe://carbide.local/{{ include "carbide-rest-site-agent.namespace" . }}/sa/{{ include "carbide-rest-site-agent.name" . }}
  issuerRef:
    name: {{ .Values.global.certificate.issuerRef.name }}
    kind: {{ .Values.global.certificate.issuerRef.kind }}
    group: {{ .Values.global.certificate.issuerRef.group }}
{{- end }}
