apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carbide-rest-site-agent.name" . }}-config
  namespace: {{ include "carbide-rest-site-agent.namespace" . }}
  labels:
    {{- include "carbide-rest-site-agent.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
