apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: elektra-site-agent
      app.kubernetes.io/component: temporal
    includeSelectors: true

resources:
  - cert.yaml
