#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

buildMetadata: [originAnnotations]

resources:
  - ../base

images:
  - name: nvcr.io/nvidian/nvforge-devel/forge-elektra
    newTag: v0.7.96-1-g7db25a1

configMapGenerator:
  - name: elektra-config-map
    behavior: merge
    env: config.properties

