# Client certificate for workflow services (API, cloud-worker, site-worker) in carbide namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-client-cert
  namespace: carbide
spec:
  secretName: temporal-client-certs
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - NVIDIA
  commonName: temporal-client
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
  dnsNames:
    - temporal-client
    - carbide-rest-api
    - cloud-worker
    - site-worker
  issuerRef:
    name: carbide-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
